#Eureka Config
eureka.client.service-url.defaultZone: http://localhost:8761/eureka

# actuator config
management:
  endpoints:
      web:
        exposure:
          include: "*"
eureka:                                                                                                                                                                       
      instance:                                                                                                                                                                   
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}   
        

#Zipkin Config
management.tracing.sampling.probability: 1.0
spring.zipkin.baseUrl: http://localhost:9411
