#Eureka Config
eureka.client.service-url.defaultZone: http://discovery-service:8761/eureka

# actuator config
management:
  endpoints:
      web:
        exposure:
          include: "*"
eureka:                                                                                                                                                                       
      instance:                                                                                                                                                                   
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}   
  tracing:
     sampling:
        probability: 1.0      


  zipkin:
     tracing:
        endpoint: http://zipkin:9411/api/v2/spans
